version: "3.9"
services:
  db:
    container_name: sql-server-db
    image: mcr.microsoft.com/mssql/server:2019-latest
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "jlptedpvuqjdyxouwifmuhauabamnfny"
      ACCEPT_EULA: "Y"
    volumes:
      - sqlvolume:/var/opt/mssql

volumes:
  sqlvolume: